<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>false</AspireUseCliBundle>
    <UserSecretsId>ca044beb-c921-4368-acda-d228bb247a4c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\uss.api\uss.api.csproj" />
    <ProjectReference Include="..\uss.ui\uss.ui.csproj" />
  </ItemGroup>

</Project>
